# Generated by Django 4.0.1 on 2022-01-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
