# Generated by Django 4.0.1 on 2022-04-01 06:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_account_current_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('code', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_data', models.JSONField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('operation', models.ForeignKey(db_column='operation_code', on_delete=django.db.models.deletion.CASCADE, to='wallet.operation')),
            ],
        ),
    ]
