# Generated by Django 4.0.1 on 2022-04-06 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_operation_alter_transaction_description_operationlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransationCategory',
            new_name='TransactionCategory',
        ),
    ]
