# Generated by Django 4.0.1 on 2022-04-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_transaction_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
